# Generated by Django 6.1 on 2026-08-29 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='observacoes',
            new_name='observacao',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_consulta',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default='2026-08-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
