# Generated by Django 6.0.7 on 2026-09-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_remove_medico_nome_medico_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], default='Agendado', max_length=20),
        ),
    ]
